/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio_3_poo;

import static ejercicio_3_poo.Ejercicio_3_POO.loadCurrencies;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TableView.TableRow;

/**
 *
 * @author Inf2
 */
public class MenuPrincipal extends javax.swing.JFrame {

    LinkedList<CuentaBancaria> cuentas = new LinkedList<CuentaBancaria>();
    LinkedList<Currency> currencies = loadCurrencies();
    CuentaBancaria cuentaEdicion = new CuentaCorriente();
    
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eliminarCuentaBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_Iban_Corriente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_Propietario_Corriente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_Intereses_Corriente = new javax.swing.JTextField();
        createCorrienteBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tf_Iban_Ahorro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_Propietario_Ahorro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_Intereses_Ahorro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_SaldoMin_Ahorro = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_Iban = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_Propietario = new javax.swing.JTextField();
        tf_Intereses = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_Saldo = new javax.swing.JTextField();
        editarCuentaBtn = new javax.swing.JButton();
        ingresarBtn = new javax.swing.JButton();
        retirarBtn = new javax.swing.JButton();
        transferirBtn = new javax.swing.JButton();
        guardarCuentaBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        monedasComboBox = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        confirmarTransferenciaBtn = new javax.swing.JButton();
        tf_Cantidad = new javax.swing.JTextField();
        label_Cantidad = new javax.swing.JLabel();
        label_Iban_Destinatario = new javax.swing.JLabel();
        tf_IbanDestinatario = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        label_Cantidad1 = new javax.swing.JLabel();
        tf_Cantidad2 = new javax.swing.JTextField();
        confirmarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuentas_lista = new javax.swing.JTable();
        editarCuentaBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 251, 251));

        texto1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        texto1.setText("CUENTAS BANCARIAS");
        texto1.setName("texto1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Cuentas bancarias");

        eliminarCuentaBtn.setBackground(new java.awt.Color(252, 126, 126));
        eliminarCuentaBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        eliminarCuentaBtn.setText("Eliminar");
        eliminarCuentaBtn.setEnabled(false);
        eliminarCuentaBtn.setName("eliminarBtn"); // NOI18N
        eliminarCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCuentaBtnActionPerformed(evt);
            }
        });

        jPanel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel7.setText("Propietario");

        tf_Iban_Corriente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel8.setText("IBAN");

        tf_Propietario_Corriente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel9.setText("Interes básico anual");

        tf_Intereses_Corriente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        createCorrienteBtn.setBackground(new java.awt.Color(163, 221, 188));
        createCorrienteBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        createCorrienteBtn.setText("Crear cuenta");
        createCorrienteBtn.setName("crearBtn"); // NOI18N
        createCorrienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCorrienteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Propietario_Corriente)
                            .addComponent(tf_Iban_Corriente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tf_Intereses_Corriente, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(createCorrienteBtn)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Propietario_Corriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Iban_Corriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Intereses_Corriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createCorrienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cuenta corriente", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel11.setText("Propietario");

        tf_Iban_Ahorro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel12.setText("IBAN");

        tf_Propietario_Ahorro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel13.setText("Interes básico anual");

        tf_Intereses_Ahorro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel14.setText("Saldo mínimo");

        tf_SaldoMin_Ahorro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        jButton6.setBackground(new java.awt.Color(163, 221, 188));
        jButton6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButton6.setText("Crear cuenta");
        jButton6.setName("crearBtn"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_Propietario_Ahorro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Iban_Ahorro))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Intereses_Ahorro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(52, 85, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tf_SaldoMin_Ahorro)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Propietario_Ahorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Iban_Ahorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Intereses_Ahorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_SaldoMin_Ahorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cuenta ahorro", jPanel3);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("Crear cuentas nuevas");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Información de cuenta seleccionada");

        tf_Iban.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tf_Iban.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel16.setText("Propietario");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel17.setText("Interes básico anual");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel15.setText("IBAN");

        tf_Propietario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tf_Propietario.setEnabled(false);

        tf_Intereses.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tf_Intereses.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel18.setText("Saldo de cuenta");

        tf_Saldo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tf_Saldo.setEnabled(false);

        editarCuentaBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        editarCuentaBtn.setText("Editar");
        editarCuentaBtn.setEnabled(false);
        editarCuentaBtn.setName("seleccionarBtn"); // NOI18N
        editarCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCuentaBtnActionPerformed(evt);
            }
        });

        ingresarBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        ingresarBtn.setText("Ingresar");
        ingresarBtn.setEnabled(false);
        ingresarBtn.setName("seleccionarBtn"); // NOI18N
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });

        retirarBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        retirarBtn.setText("Retirar");
        retirarBtn.setEnabled(false);
        retirarBtn.setName("seleccionarBtn"); // NOI18N
        retirarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBtnActionPerformed(evt);
            }
        });

        transferirBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        transferirBtn.setText("Transferencia");
        transferirBtn.setEnabled(false);
        transferirBtn.setName("seleccionarBtn"); // NOI18N
        transferirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirBtnActionPerformed(evt);
            }
        });

        guardarCuentaBtn.setBackground(new java.awt.Color(163, 221, 188));
        guardarCuentaBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        guardarCuentaBtn.setText("Guardar");
        guardarCuentaBtn.setEnabled(false);
        guardarCuentaBtn.setName("crearBtn"); // NOI18N
        guardarCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCuentaBtnActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel19.setText("Moneda");

        monedasComboBox.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        monedasComboBox.setEnabled(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transferencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N

        confirmarTransferenciaBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        confirmarTransferenciaBtn.setText("Confirmar transferencia");
        confirmarTransferenciaBtn.setEnabled(false);
        confirmarTransferenciaBtn.setName("seleccionarBtn"); // NOI18N
        confirmarTransferenciaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarTransferenciaBtnActionPerformed(evt);
            }
        });

        tf_Cantidad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tf_Cantidad.setEnabled(false);

        label_Cantidad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        label_Cantidad.setText("Cantidad");
        label_Cantidad.setOpaque(true);

        label_Iban_Destinatario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        label_Iban_Destinatario.setText("IBAN destinatario");
        label_Iban_Destinatario.setOpaque(true);

        tf_IbanDestinatario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tf_IbanDestinatario.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_Iban_Destinatario)
                    .addComponent(label_Cantidad)
                    .addComponent(confirmarTransferenciaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(tf_Cantidad)
                    .addComponent(tf_IbanDestinatario))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Iban_Destinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_IbanDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_Cantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarTransferenciaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar / Retirar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N

        label_Cantidad1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        label_Cantidad1.setText("Cantidad");
        label_Cantidad1.setOpaque(true);

        tf_Cantidad2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tf_Cantidad2.setEnabled(false);

        confirmarBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        confirmarBtn.setText("Confirmar");
        confirmarBtn.setEnabled(false);
        confirmarBtn.setName("seleccionarBtn"); // NOI18N
        confirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(confirmarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Cantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_Cantidad1))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Cantidad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Cantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cuentas_lista.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cuentas_lista.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        cuentas_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Propietario", "IBAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cuentas_lista.setColumnSelectionAllowed(true);
        cuentas_lista.getTableHeader().setReorderingAllowed(false);
        cuentas_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentas_listaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cuentas_lista);
        cuentas_lista.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        editarCuentaBtn1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        editarCuentaBtn1.setText("Refrescar");
        editarCuentaBtn1.setActionCommand("");
        editarCuentaBtn1.setName("seleccionarBtn"); // NOI18N
        editarCuentaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCuentaBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarCuentaBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_Iban, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Intereses, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(tf_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(monedasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(guardarCuentaBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transferirBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ingresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(retirarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Iban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Intereses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monedasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(retirarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardarCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transferirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarCuentaBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCuentaBtnActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Eliminar cuenta " + tf_Iban.getText() + " ?", "Seleccione", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) {
            cuentas.remove(getCuentaBancaria(tf_Iban.getText()));
            JOptionPane.showMessageDialog(this, 
                    "Eliminado satisfactoriamente");
        }
    }//GEN-LAST:event_eliminarCuentaBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void editarCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCuentaBtnActionPerformed
        cuentaEdicion = getCuentaBancaria(tf_Iban.getText());
        cuentas.remove(cuentaEdicion);
        // BOTONES
        editarCuentaBtn.setEnabled(false);
        eliminarCuentaBtn.setEnabled(true);
        guardarCuentaBtn.setEnabled(true);
        retirarBtn.setEnabled(false);
        ingresarBtn.setEnabled(false);
        tf_Cantidad2.setEnabled(false);
        confirmarBtn.setEnabled(false);
        tf_IbanDestinatario.setEnabled(false);
        tf_Cantidad.setEnabled(false);
        confirmarTransferenciaBtn.setEnabled(false);
        transferirBtn.setEnabled(false);
        // TEXT FIELDS & COMBO BOX
        tf_Propietario.setEnabled(true);
        tf_Iban.setEnabled(true);
        tf_Intereses.setEnabled(true);
        monedasComboBox.setEnabled(true);
        
    }//GEN-LAST:event_editarCuentaBtnActionPerformed

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        ingresarRetirarBtns(true);
    }//GEN-LAST:event_ingresarBtnActionPerformed

    public void ingresarRetirarBtns(boolean esIngresar) {
        editarCuentaBtn.setEnabled(false);
        eliminarCuentaBtn.setEnabled(false);
        guardarCuentaBtn.setEnabled(false);
            
        if (esIngresar) {
            retirarBtn.setEnabled(true);
            ingresarBtn.setEnabled(false);
        } else {
            retirarBtn.setEnabled(false);
            ingresarBtn.setEnabled(true);
        }
            
        tf_Cantidad2.setEnabled(true);
        confirmarBtn.setEnabled(true);
        
    }
    
    private void retirarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBtnActionPerformed
        ingresarRetirarBtns(false);
    }//GEN-LAST:event_retirarBtnActionPerformed

    private void transferirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirBtnActionPerformed
        if (transferirBtn.getText().equals("Transferencia")) {
            editarCuentaBtn.setEnabled(false);
            eliminarCuentaBtn.setEnabled(false);
            guardarCuentaBtn.setEnabled(false);
        
            ingresarBtn.setEnabled(false);
            retirarBtn.setEnabled(false);
            
            tf_IbanDestinatario.setEnabled(true);
            tf_Cantidad.setEnabled(true);
            confirmarTransferenciaBtn.setEnabled(true);
            transferirBtn.setText("Cancelar");
        } else {
            tf_IbanDestinatario.setText("");
            tf_Cantidad.setText("");
            transferirBtn.setText("Transferencia");
            activateAccountBtns();
        }
        
    }//GEN-LAST:event_transferirBtnActionPerformed

    private void guardarCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCuentaBtnActionPerformed
        CuentaBancaria cb = cuentaEdicion;
        cuentas.remove(cb);
        
        if (!(cb.getCurrency().getName().equals(monedasComboBox.getSelectedItem()))) {
            for (Currency c : currencies) {
                if (c.getName().equals(monedasComboBox.getSelectedItem())) {
                    cb.convertirSaldo(c);
                    cb.setCurrency(c);
                }
            }
        }
        
        cb.setPropietario(tf_Propietario.getText());
        cb.setIban(tf_Iban.getText());
        
        cuentas.add(cb);
        refreshAccounts();
        selectAccount(cb);
        
        JOptionPane.showMessageDialog(this, "Se ha guardado la cuenta satisfactoriamente");
    }//GEN-LAST:event_guardarCuentaBtnActionPerformed

    private void confirmarTransferenciaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarTransferenciaBtnActionPerformed
        if (!(tf_IbanDestinatario.getText().isEmpty() && !(tf_Cantidad.getText().isEmpty()))) {
            CuentaBancaria cb = getCuentaBancaria(tf_Iban.getText());
            cuentas.remove(cb);
            try {
                cb.transferir(cuentas, tf_IbanDestinatario.getText(), Double.parseDouble(tf_Cantidad.getText()));
                JOptionPane.showMessageDialog(this, "Transferencia completada satisfactoriamente");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            cuentas.add(cb);
            selectAccount(cb);
            transferirBtn.setText("Transferencia");
        } 
    }//GEN-LAST:event_confirmarTransferenciaBtnActionPerformed

    private void createCorrienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCorrienteBtnActionPerformed
        // CREAR CUENTA CORRIENTE
        if (!(tf_Propietario_Corriente.getText().isEmpty()) && !(tf_Iban_Corriente.getText().isEmpty()) && !(tf_Intereses_Corriente.getText().isEmpty())) {
            CuentaBancaria cb = new CuentaCorriente(tf_Propietario_Corriente.getText(), tf_Iban_Corriente.getText(), Double.parseDouble(tf_Intereses_Corriente.getText()));
            cuentas.add(cb);
            tf_Propietario_Corriente.setText("");
            tf_Iban_Corriente.setText("");
            tf_Intereses_Corriente.setText("");
            refreshAccounts();
        } else {
            JOptionPane.showMessageDialog(this, "Información insuficiente");
        }
    }//GEN-LAST:event_createCorrienteBtnActionPerformed

    private void confirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBtnActionPerformed
        if (!(tf_Cantidad2.getText().isEmpty())) {
            CuentaBancaria cb = getCuentaBancaria(tf_Iban.getText());
            cuentas.remove(cb);
            try{
                if (ingresarBtn.isEnabled()) {
                    cb.retirar(Double.parseDouble(tf_Cantidad2.getText()));
                } else {
                    cb.ingresar(Double.parseDouble(tf_Cantidad2.getText()));
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            cuentas.add(cb);
            tf_Cantidad.setText("");
            tf_IbanDestinatario.setText("");
            selectAccount(cb);

        }
    }//GEN-LAST:event_confirmarBtnActionPerformed

    private void cuentas_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentas_listaMouseClicked
        int index = cuentas_lista.getSelectedRow();
        String[] rowData = new String[cuentas_lista.getColumnCount()];
        if (evt.getClickCount() == 2){
            // LEER FILA
            for (int i=0; i < cuentas_lista.getColumnCount(); i++) {
                rowData[i] = (String) cuentas_lista.getValueAt(index, i);
            }
            // SELECCIONAR CUENTA
            selectAccount(getCuentaBancaria(rowData[1]));
        }
    }//GEN-LAST:event_cuentas_listaMouseClicked

    private void editarCuentaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCuentaBtn1ActionPerformed
        refreshAccounts();
    }//GEN-LAST:event_editarCuentaBtn1ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set System L&F
        UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } 
        catch (UnsupportedLookAndFeelException e) {
       // handle exception
        }
        catch (ClassNotFoundException e) {
       // handle exception
        }
        catch (InstantiationException e) {
       // handle exception
        }
        catch (IllegalAccessException e) {
       // handle exception
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    public void selectAccount(CuentaBancaria cb) {
        reloadComboBox();
        tf_Propietario.setText(cb.getPropietario());
        tf_Iban.setText(cb.getIban());
        tf_Intereses.setText("" + cb.getInteresAnualBasico());
        tf_Saldo.setText("" + cb.getSaldo() + " " + cb.getCurrencySign());
        activateAccountBtns();
        for (int i=0; i < monedasComboBox.getItemCount(); i++) {
            if (monedasComboBox.getItemAt(i).equals(cb.getCurrency().getName())) {
                monedasComboBox.setSelectedIndex(i);
            }
        }
    }
    
    public void reloadComboBox() {
        monedasComboBox.removeAllItems();
        for (Currency c : currencies) {
            monedasComboBox.addItem(c.getName());
        }
    }
    
    public void activateAccountBtns() {
        editarCuentaBtn.setEnabled(true);
        eliminarCuentaBtn.setEnabled(true);
        guardarCuentaBtn.setEnabled(false);
        ingresarBtn.setEnabled(true);
        retirarBtn.setEnabled(true);
        transferirBtn.setEnabled(true);
        confirmarTransferenciaBtn.setEnabled(false);
        tf_IbanDestinatario.setEnabled(false);
        tf_Cantidad.setEnabled(false);
        tf_Cantidad2.setEnabled(false);
        confirmarBtn.setEnabled(false);
        tf_Propietario.setEnabled(false);
        tf_Iban.setEnabled(false);
        tf_Intereses.setEnabled(false);
        monedasComboBox.setEnabled(false);
    }
    
    public void deactivateAccountBtns() {
        editarCuentaBtn.setEnabled(false);
        eliminarCuentaBtn.setEnabled(false);
        guardarCuentaBtn.setEnabled(false);
        ingresarBtn.setEnabled(false);
        retirarBtn.setEnabled(false);
        transferirBtn.setEnabled(false);
        confirmarTransferenciaBtn.setEnabled(false);
        tf_IbanDestinatario.setEnabled(false);
        tf_Cantidad.setEnabled(false);
        tf_Cantidad2.setEnabled(false);
        confirmarBtn.setEnabled(false);
        tf_Propietario.setEnabled(false);
        tf_Iban.setEnabled(false);
        tf_Intereses.setEnabled(false);
        monedasComboBox.setEnabled(false);
    }

    public CuentaBancaria getCuentaBancaria(String iban) {
        for (CuentaBancaria cb : cuentas) {
            if (cb.getIban().equals(iban)) {
                return cb;
            }
        }
        return null;
    }
    
    public void clearSelection() {
        tf_Propietario.setText("");
        tf_Iban.setText("");
        tf_Intereses.setText("");
        tf_Saldo.setText("");
        deactivateAccountBtns();
    }
    
    public void refreshAccounts() {  
        
        DefaultTableModel model = (DefaultTableModel) cuentas_lista.getModel();
        // ELIMINAR LISTA
        System.out.println("Existen " + cuentas_lista.getRowCount() + " filas");
        
        for (int i=1; i < cuentas_lista.getRowCount()+1; i++) {
            System.out.println("Eliminando " + i);
            model.removeRow(i-1);            
        }
        // LLENAR LISTA
        for (CuentaBancaria cb : cuentas) {
            System.out.println("Añadiendo " + cb.getIban());
            model.addRow(new Object[]{cb.getPropietario(), cb.getIban()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarBtn;
    private javax.swing.JButton confirmarTransferenciaBtn;
    private javax.swing.JButton createCorrienteBtn;
    private javax.swing.JTable cuentas_lista;
    private javax.swing.JButton editarCuentaBtn;
    private javax.swing.JButton editarCuentaBtn1;
    private javax.swing.JButton eliminarCuentaBtn;
    private javax.swing.JButton guardarCuentaBtn;
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_Cantidad;
    private javax.swing.JLabel label_Cantidad1;
    private javax.swing.JLabel label_Iban_Destinatario;
    private javax.swing.JComboBox<String> monedasComboBox;
    private javax.swing.JButton retirarBtn;
    private javax.swing.JLabel texto1;
    private javax.swing.JTextField tf_Cantidad;
    private javax.swing.JTextField tf_Cantidad2;
    private javax.swing.JTextField tf_Iban;
    private javax.swing.JTextField tf_IbanDestinatario;
    private javax.swing.JTextField tf_Iban_Ahorro;
    private javax.swing.JTextField tf_Iban_Corriente;
    private javax.swing.JTextField tf_Intereses;
    private javax.swing.JTextField tf_Intereses_Ahorro;
    private javax.swing.JTextField tf_Intereses_Corriente;
    private javax.swing.JTextField tf_Propietario;
    private javax.swing.JTextField tf_Propietario_Ahorro;
    private javax.swing.JTextField tf_Propietario_Corriente;
    private javax.swing.JTextField tf_Saldo;
    private javax.swing.JTextField tf_SaldoMin_Ahorro;
    private javax.swing.JButton transferirBtn;
    // End of variables declaration//GEN-END:variables
}
