package Game;

import java.io.File;
import java.io.IOException;
import java.util.InputMismatchException;
import java.util.logging.Level;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 * This is the visual display that shows the game.
 * @author Cedric Christoph
 * @since 1.0.0
 * @version 1.1.0
 */
public class Display extends javax.swing.JFrame {

    /**
     * Playground for each player (just needed in the preparation windows).
     */
    protected Playground playgroundOne, playgroundTwo;

    /**
     * Interpretor for converting Strings to maps for Playgrounds.
     */
    protected Interpretor interpretor = new Interpretor();
    
    /**
     * Game.
     */
    protected Game partida;
    
    /**
     * Logger used for saving and loading game files.
     */
    protected Logger logger;
    
    /**
     * IconLoader used for properly load icons into the JButtons.
     */
    protected IconLoader iLoader;
    
    /**
     * AudioPlayer for playing sound effects.
     */
    protected AudioPlayer player = new AudioPlayer();
    
    /**
     * Boolean which saves if the last shot hitted a ship or not.
     */
    protected boolean lastHitted;
    
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        fileChooserOpen = new javax.swing.JFileChooser();
        tabs = new javax.swing.JTabbedPane();
        MenuPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        crearPartida = new javax.swing.JButton();
        cargar = new javax.swing.JButton();
        p1_preparation = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        player_one_prep_ships = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        p2_preparation = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        player_two_prep_ships = new javax.swing.JTextArea();
        game = new javax.swing.JPanel();
        turnLabel = new javax.swing.JLabel();
        zero_0 = new javax.swing.JButton();
        zero_1 = new javax.swing.JButton();
        zero_2 = new javax.swing.JButton();
        zero_3 = new javax.swing.JButton();
        zero_4 = new javax.swing.JButton();
        zero_5 = new javax.swing.JButton();
        zero_6 = new javax.swing.JButton();
        zero_7 = new javax.swing.JButton();
        one_0 = new javax.swing.JButton();
        one_1 = new javax.swing.JButton();
        one_2 = new javax.swing.JButton();
        one_3 = new javax.swing.JButton();
        one_4 = new javax.swing.JButton();
        one_5 = new javax.swing.JButton();
        one_6 = new javax.swing.JButton();
        one_7 = new javax.swing.JButton();
        two_0 = new javax.swing.JButton();
        two_1 = new javax.swing.JButton();
        two_2 = new javax.swing.JButton();
        two_3 = new javax.swing.JButton();
        two_4 = new javax.swing.JButton();
        two_5 = new javax.swing.JButton();
        two_6 = new javax.swing.JButton();
        two_7 = new javax.swing.JButton();
        three_0 = new javax.swing.JButton();
        three_1 = new javax.swing.JButton();
        three_2 = new javax.swing.JButton();
        three_3 = new javax.swing.JButton();
        three_4 = new javax.swing.JButton();
        three_5 = new javax.swing.JButton();
        three_6 = new javax.swing.JButton();
        three_7 = new javax.swing.JButton();
        four_0 = new javax.swing.JButton();
        four_1 = new javax.swing.JButton();
        four_2 = new javax.swing.JButton();
        four_3 = new javax.swing.JButton();
        four_4 = new javax.swing.JButton();
        four_5 = new javax.swing.JButton();
        four_6 = new javax.swing.JButton();
        four_7 = new javax.swing.JButton();
        five_0 = new javax.swing.JButton();
        five_1 = new javax.swing.JButton();
        five_2 = new javax.swing.JButton();
        five_3 = new javax.swing.JButton();
        five_4 = new javax.swing.JButton();
        five_5 = new javax.swing.JButton();
        five_6 = new javax.swing.JButton();
        five_7 = new javax.swing.JButton();
        six_0 = new javax.swing.JButton();
        six_1 = new javax.swing.JButton();
        six_2 = new javax.swing.JButton();
        six_3 = new javax.swing.JButton();
        six_4 = new javax.swing.JButton();
        six_5 = new javax.swing.JButton();
        six_6 = new javax.swing.JButton();
        six_7 = new javax.swing.JButton();
        seven_0 = new javax.swing.JButton();
        seven_1 = new javax.swing.JButton();
        seven_2 = new javax.swing.JButton();
        seven_3 = new javax.swing.JButton();
        seven_4 = new javax.swing.JButton();
        seven_5 = new javax.swing.JButton();
        seven_6 = new javax.swing.JButton();
        seven_7 = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        nextBtn1 = new javax.swing.JButton();
        p2_attack_p1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        fileChooserOpen.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        fileChooserOpen.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel1.setText("Hundir la flota");

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        crearPartida.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        crearPartida.setText("Nueva partida");
        crearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPartidaActionPerformed(evt);
            }
        });

        cargar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        cargar.setText("Cargar partida");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPaneLayout = new javax.swing.GroupLayout(MenuPane);
        MenuPane.setLayout(MenuPaneLayout);
        MenuPaneLayout.setHorizontalGroup(
            MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPaneLayout.createSequentialGroup()
                .addGroup(MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPaneLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(MenuPaneLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPaneLayout.setVerticalGroup(
            MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPaneLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(crearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        tabs.addTab("menu", MenuPane);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel2.setText("Player One Preparation");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel3.setText("You must place 2 large ships, 2 medium ships and one small ship");

        player_one_prep_ships.setColumns(20);
        player_one_prep_ships.setFont(new java.awt.Font("Monospaced", 0, 30)); // NOI18N
        player_one_prep_ships.setRows(5);
        player_one_prep_ships.setText("   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |");
        jScrollPane1.setViewportView(player_one_prep_ships);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("Write S for ship where you want");

        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButton3.setText("Next >");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1_preparationLayout = new javax.swing.GroupLayout(p1_preparation);
        p1_preparation.setLayout(p1_preparationLayout);
        p1_preparationLayout.setHorizontalGroup(
            p1_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1_preparationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1_preparationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(p1_preparationLayout.createSequentialGroup()
                        .addGroup(p1_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p1_preparationLayout.setVerticalGroup(
            p1_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1_preparationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("p1_preparation", p1_preparation);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel5.setText("Player Two Preparation");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel6.setText("You must place 2 large ships, 2 medium ships and one small ship");

        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButton4.setText("Start >");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel8.setText("Write S for ship where you want");

        player_two_prep_ships.setColumns(20);
        player_two_prep_ships.setFont(new java.awt.Font("Monospaced", 0, 30)); // NOI18N
        player_two_prep_ships.setRows(5);
        player_two_prep_ships.setText("   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |\n   |   |   |   |   |   |   |   |");
        jScrollPane3.setViewportView(player_two_prep_ships);

        javax.swing.GroupLayout p2_preparationLayout = new javax.swing.GroupLayout(p2_preparation);
        p2_preparation.setLayout(p2_preparationLayout);
        p2_preparationLayout.setHorizontalGroup(
            p2_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2_preparationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2_preparationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p2_preparationLayout.createSequentialGroup()
                        .addGroup(p2_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        p2_preparationLayout.setVerticalGroup(
            p2_preparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2_preparationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("p2_preparation", p2_preparation);

        turnLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        turnLabel.setText("Turn: ");

        zero_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_0ActionPerformed(evt);
            }
        });

        zero_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_1ActionPerformed(evt);
            }
        });

        zero_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_2ActionPerformed(evt);
            }
        });

        zero_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_3ActionPerformed(evt);
            }
        });

        zero_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_4ActionPerformed(evt);
            }
        });

        zero_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_5ActionPerformed(evt);
            }
        });

        zero_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_6ActionPerformed(evt);
            }
        });

        zero_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_7ActionPerformed(evt);
            }
        });

        one_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_0ActionPerformed(evt);
            }
        });

        one_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_1ActionPerformed(evt);
            }
        });

        one_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_2ActionPerformed(evt);
            }
        });

        one_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_3ActionPerformed(evt);
            }
        });

        one_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_4ActionPerformed(evt);
            }
        });

        one_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_5ActionPerformed(evt);
            }
        });

        one_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_6ActionPerformed(evt);
            }
        });

        one_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_7ActionPerformed(evt);
            }
        });

        two_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_0ActionPerformed(evt);
            }
        });

        two_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_1ActionPerformed(evt);
            }
        });

        two_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_2ActionPerformed(evt);
            }
        });

        two_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_3ActionPerformed(evt);
            }
        });

        two_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_4ActionPerformed(evt);
            }
        });

        two_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_5ActionPerformed(evt);
            }
        });

        two_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_6ActionPerformed(evt);
            }
        });

        two_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_7ActionPerformed(evt);
            }
        });

        three_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_0ActionPerformed(evt);
            }
        });

        three_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_1ActionPerformed(evt);
            }
        });

        three_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_2ActionPerformed(evt);
            }
        });

        three_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_3ActionPerformed(evt);
            }
        });

        three_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_4ActionPerformed(evt);
            }
        });

        three_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_5ActionPerformed(evt);
            }
        });

        three_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_6ActionPerformed(evt);
            }
        });

        three_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_7ActionPerformed(evt);
            }
        });

        four_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_0ActionPerformed(evt);
            }
        });

        four_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_1ActionPerformed(evt);
            }
        });

        four_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_2ActionPerformed(evt);
            }
        });

        four_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_3ActionPerformed(evt);
            }
        });

        four_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_4ActionPerformed(evt);
            }
        });

        four_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_5ActionPerformed(evt);
            }
        });

        four_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_6ActionPerformed(evt);
            }
        });

        four_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_7ActionPerformed(evt);
            }
        });

        five_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_0ActionPerformed(evt);
            }
        });

        five_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_1ActionPerformed(evt);
            }
        });

        five_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_2ActionPerformed(evt);
            }
        });

        five_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_3ActionPerformed(evt);
            }
        });

        five_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_4ActionPerformed(evt);
            }
        });

        five_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_5ActionPerformed(evt);
            }
        });

        five_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_6ActionPerformed(evt);
            }
        });

        five_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_7ActionPerformed(evt);
            }
        });

        six_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_0ActionPerformed(evt);
            }
        });

        six_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_1ActionPerformed(evt);
            }
        });

        six_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_2ActionPerformed(evt);
            }
        });

        six_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_3ActionPerformed(evt);
            }
        });

        six_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_4ActionPerformed(evt);
            }
        });

        six_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_5ActionPerformed(evt);
            }
        });

        six_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_6ActionPerformed(evt);
            }
        });

        six_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_7ActionPerformed(evt);
            }
        });

        seven_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_0ActionPerformed(evt);
            }
        });

        seven_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_1ActionPerformed(evt);
            }
        });

        seven_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_2ActionPerformed(evt);
            }
        });

        seven_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_3ActionPerformed(evt);
            }
        });

        seven_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_4ActionPerformed(evt);
            }
        });

        seven_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_5ActionPerformed(evt);
            }
        });

        seven_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_6ActionPerformed(evt);
            }
        });

        seven_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_7ActionPerformed(evt);
            }
        });

        nextBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        nextBtn.setText("Next >>");
        nextBtn.setEnabled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        nextBtn1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        nextBtn1.setText("Save");
        nextBtn1.setActionCommand("");
        nextBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameLayout = new javax.swing.GroupLayout(game);
        game.setLayout(gameLayout);
        gameLayout.setHorizontalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameLayout.createSequentialGroup()
                .addComponent(nextBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(gameLayout.createSequentialGroup()
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(one_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(zero_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(two_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(three_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(four_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(four_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(four_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(four_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(four_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(five_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(six_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(six_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(six_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(six_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(six_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(seven_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seven_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seven_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seven_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seven_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(gameLayout.createSequentialGroup()
                                    .addComponent(zero_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zero_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zero_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameLayout.createSequentialGroup()
                                    .addComponent(two_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(two_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(two_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameLayout.createSequentialGroup()
                                    .addComponent(one_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(one_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(one_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameLayout.createSequentialGroup()
                                    .addComponent(three_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(three_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(three_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameLayout.createSequentialGroup()
                                    .addComponent(four_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(four_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(four_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameLayout.createSequentialGroup()
                                    .addComponent(five_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(five_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(five_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameLayout.createSequentialGroup()
                                    .addComponent(six_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(six_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(six_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(gameLayout.createSequentialGroup()
                                .addComponent(seven_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seven_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seven_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(gameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        gameLayout.setVerticalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zero_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(one_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(two_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(three_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(four_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(five_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(six_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seven_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 43, Short.MAX_VALUE)
                .addGroup(gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tabs.addTab("game", game);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        jLabel7.setText("¡ Victoria !");

        winnerLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N

        jButton5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButton5.setText("Jugar de nuevo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButton6.setText("Volver al menú");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2_attack_p1Layout = new javax.swing.GroupLayout(p2_attack_p1);
        p2_attack_p1.setLayout(p2_attack_p1Layout);
        p2_attack_p1Layout.setHorizontalGroup(
            p2_attack_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2_attack_p1Layout.createSequentialGroup()
                .addGroup(p2_attack_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2_attack_p1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel7))
                    .addGroup(p2_attack_p1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(winnerLabel))
                    .addGroup(p2_attack_p1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(p2_attack_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        p2_attack_p1Layout.setVerticalGroup(
            p2_attack_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2_attack_p1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(winnerLabel)
                .addGap(50, 50, 50)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        tabs.addTab("victoria", p2_attack_p1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabs.getAccessibleContext().setAccessibleName("menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exits the program
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Starts a new game
     * @param evt 
     */
    private void crearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPartidaActionPerformed
        reset();
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_crearPartidaActionPerformed

    /**
     * Finishes player one's preparation
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        playgroundOne = new Playground("Player One", interpretor.convert(player_one_prep_ships.getText()));
        tabs.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Finishes player two's preparation and starts the game
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        playgroundTwo = new Playground("Player Two", interpretor.convert(player_two_prep_ships.getText()));
        partida = new Game(playgroundOne, playgroundTwo);
        showTurn();
        cargarHistorial();
        tabs.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Finishes the turn and switches it
     * @param evt 
     */
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        switchTurn();
        nextBtn.setEnabled(false);
    }//GEN-LAST:event_nextBtnActionPerformed

    /*
     *  Every JButton shoots at it's location on the playground and saves the returned value
     *  in lastHitted. After that, it executes cargarHistorial.
     */
    private void six_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_7ActionPerformed
        lastHitted = partida.shoot(6, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_six_7ActionPerformed

    private void zero_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_0ActionPerformed
        lastHitted = partida.shoot(0, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_0ActionPerformed

    private void zero_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_1ActionPerformed
        lastHitted = partida.shoot(0, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_1ActionPerformed

    private void zero_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_2ActionPerformed
        lastHitted = partida.shoot(0, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_2ActionPerformed

    private void zero_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_3ActionPerformed
         lastHitted = partida.shoot(0, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_3ActionPerformed

    private void zero_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_4ActionPerformed
        // TODO add your handling code here:
         lastHitted = partida.shoot(0, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_4ActionPerformed

    private void zero_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_5ActionPerformed
        // TODO add your handling code here:
         lastHitted = partida.shoot(0, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_5ActionPerformed

    private void zero_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_6ActionPerformed
        // TODO add your handling code here:
         lastHitted = partida.shoot(0, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_6ActionPerformed

    private void zero_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_7ActionPerformed
        // TODO add your handling code here:
         lastHitted = partida.shoot(0, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_zero_7ActionPerformed

    private void one_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_0ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_one_0ActionPerformed

    private void one_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_1ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_one_1ActionPerformed

    private void one_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_2ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_one_2ActionPerformed

    private void one_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_3ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_one_3ActionPerformed

    private void one_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_4ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_one_4ActionPerformed

    private void one_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_5ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_one_5ActionPerformed

    private void one_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_6ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_one_6ActionPerformed

    private void one_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_7ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(1, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_one_7ActionPerformed

    private void two_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_0ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_two_0ActionPerformed

    private void two_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_1ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_two_1ActionPerformed

    private void two_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_2ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_two_2ActionPerformed

    private void two_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_3ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_two_3ActionPerformed

    private void two_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_4ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_two_4ActionPerformed

    private void two_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_5ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_two_5ActionPerformed

    private void two_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_6ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_two_6ActionPerformed

    private void two_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_7ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(2, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_two_7ActionPerformed

    private void three_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_0ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_three_0ActionPerformed

    private void three_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_1ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_three_1ActionPerformed

    private void three_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_2ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_three_2ActionPerformed

    private void three_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_3ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_three_3ActionPerformed

    private void three_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_4ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_three_4ActionPerformed

    private void three_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_5ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_three_5ActionPerformed

    private void three_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_6ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_three_6ActionPerformed

    private void three_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_7ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(3, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_three_7ActionPerformed

    private void four_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_0ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_four_0ActionPerformed

    private void four_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_1ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_four_1ActionPerformed

    private void four_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_2ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_four_2ActionPerformed

    private void four_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_3ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_four_3ActionPerformed

    private void four_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_4ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_four_4ActionPerformed

    private void four_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_5ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_four_5ActionPerformed

    private void four_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_6ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_four_6ActionPerformed

    private void four_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_7ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(4, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_four_7ActionPerformed

    private void five_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_0ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_five_0ActionPerformed

    private void five_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_1ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_five_1ActionPerformed

    private void five_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_2ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_five_2ActionPerformed

    private void five_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_3ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_five_3ActionPerformed

    private void five_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_4ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_five_4ActionPerformed

    private void five_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_5ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_five_5ActionPerformed

    private void five_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_6ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_five_6ActionPerformed

    private void five_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_7ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(5, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_five_7ActionPerformed

    private void six_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_0ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(6, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_six_0ActionPerformed

    private void six_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_1ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(6, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_six_1ActionPerformed

    private void six_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_2ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(6, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_six_2ActionPerformed

    private void six_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_3ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(6, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_six_3ActionPerformed

    private void six_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_4ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(6, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_six_4ActionPerformed

    private void six_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_5ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(6, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_six_5ActionPerformed

    private void six_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_6ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(6, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_six_6ActionPerformed

    private void seven_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_0ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 0);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_0ActionPerformed

    private void seven_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_1ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 1);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_1ActionPerformed

    private void seven_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_2ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 2);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_2ActionPerformed

    private void seven_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_3ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 3);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_3ActionPerformed

    private void seven_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_4ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 4);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_4ActionPerformed

    private void seven_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_5ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 5);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_5ActionPerformed

    private void seven_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_6ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 6);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_6ActionPerformed

    private void seven_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_7ActionPerformed
        // TODO add your handling code here:
        lastHitted = partida.shoot(7, 7);
        cargarHistorial();
        
    }//GEN-LAST:event_seven_7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        reset();
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        reset();
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nextBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn1ActionPerformed
        fileChooser.setCurrentDirectory(new File("."));
        fileChooser.showSaveDialog(this);
        logger = new Logger(fileChooser.getSelectedFile());
        if (logger.save(partida)) 
            JOptionPane.showMessageDialog(this, "Game has been saved succesfully", "Game saved", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Error while trying to save the game. Game hasn't been saved.", "Error", JOptionPane.ERROR_MESSAGE);
        tabs.setSelectedIndex(0);
        reset();
    }//GEN-LAST:event_nextBtn1ActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        reset();
        fileChooserOpen.setCurrentDirectory(new File("."));
        fileChooserOpen.showOpenDialog(this);
        logger = new Logger(fileChooserOpen.getSelectedFile());
        try {
            partida = new Game(logger.load());
            tabs.setSelectedIndex(3);
            showTurn();
            cargarHistorial();
        } catch (InputMismatchException imm) {
            System.out.println(imm.toString());
        }
    }//GEN-LAST:event_cargarActionPerformed

    /**
     * Exits the program
     * @param evt 
     */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed
    
    /**
     * Method used for resetting the text areas in the player preparation windows and stopping the audio player.
     * @since 1.0.0
     */
    public void reset() {
        String ships = 
            "   |   |   |   |   |   |   |   |\n" +
            "   |   |   |   |   |   |   |   |\n" +
            "   |   |   |   |   |   |   |   |\n" +
            "   |   |   |   |   |   |   |   |\n" +
            "   |   |   |   |   |   |   |   |\n" +
            "   |   |   |   |   |   |   |   |\n" +
            "   |   |   |   |   |   |   |   |\n" +
            "   |   |   |   |   |   |   |   |";
        
        player_one_prep_ships.setText(ships);
        player_two_prep_ships.setText(ships);
        if (player.isPlaying())
            player.stop();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }
    
    /**
     * Method used for switching player turn
     * @since 1.0.0
     */
    public void switchTurn() {
        player.disable();
        partida.switchTurn();
        showTurn();
        cargarHistorial();
        player.enable();
    }
    
    /**
     * Method used for showing which player has the turn
     * @since 1.0.0
     */
    public void showTurn() {
        if (partida.getTurn() == partida.TURN_PLAYER_ONE())
            turnLabel.setText("Jugador 1");
        else
            turnLabel.setText("Jugador 2");
    }
    
    /**
     * Method used to properly load each players previous moves
     * @since 1.0.0
     */
    public void cargarHistorial() {
        try {
            iLoader = new IconLoader();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }
        Field[][] map = partida.getActivePlayground().getMap();
        JButton[][] botones = getButtonList();
        for (int i=0; i<8; i++) {
            for (int j=0; j<8; j++) {
                String valor = map[i][j].toString();
                switch(valor){
                    case "X":
                        botones[i][j].setIcon(iLoader.getExplosion(botones[i][j].getWidth(), botones[i][j].getHeight()));
                        break;
                    case "0":
                        botones[i][j].setIcon(iLoader.getWater(botones[i][j].getWidth(), botones[i][j].getHeight()));
                        break;
                    case " ":
                        botones[i][j].setIcon(iLoader.getGreyWater(botones[i][j].getWidth(), botones[i][j].getHeight()));
                        break;
                }
                //botones[i][j].setText(valor);
            }
        }
        if (lastHitted) {
            partida.setFinished(false);
            player.explosion();
        } else {
            player.water();
        }
        
        if (partida.getFinished())
            nextBtn.setEnabled(true);
        else
            nextBtn.setEnabled(false);   
        
        if (partida.allShipsDestroyed()) {
            winnerLabel.setText("Los barcos de " + partida.getActivePlayground().getPlayer() + " han sido destruidos !!!");
            tabs.setSelectedIndex(4);
            player.victory();
        }
    }

    /**
     * Method for eliminating the text inside the map buttons.
     * @since 1.0.0
     * @deprecated 
     */
    public void clearButtons() {
        for (JButton[] fila : getButtonList()) {
            for (JButton boton : fila) {
                boton.setText("");
            }
        }
    }
    
    /**
     * Method for turning off all map buttons.
     * @since 1.0.0
     * @deprecated 
     */
    public void turnOffButtons() {
        for (JButton[] fila : getButtonList()) {
            for (JButton boton : fila) {
                boton.setEnabled(false);
            }
        }
    }
    
    /**
     * Method for turning on all buttons.
     * @since 1.0.0
     * @deprecated 
     */
    public void turnOnButtons() {
        for (JButton[] fila : getButtonList()) {
            for (JButton boton : fila) {
                boton.setEnabled(true);
            }
        }
    }
    
    /**
     * Function that returns all JButtons of the map for easier access
     * @return JButton array
     */
    public JButton[][] getButtonList() {
        JButton[][] botones = {
            {zero_0, zero_1, zero_2, zero_3, zero_4, zero_5, zero_6, zero_7},
            {one_0, one_1, one_2, one_3, one_4, one_5, one_6, one_7},
            {two_0, two_1, two_2, two_3, two_4, two_5, two_6, two_7},
            {three_0, three_1, three_2, three_3, three_4, three_5, three_6, three_7},
            {four_0, four_1, four_2, four_3, four_4, four_5, four_6, four_7},
            {five_0, five_1, five_2, five_3, five_4, five_5, five_6, five_7},
            {six_0, six_1, six_2, six_3, six_4, six_5, six_6, six_7},
            {seven_0, seven_1, seven_2, seven_3, seven_4, seven_5, seven_6, seven_7}
        };
        return botones;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPane;
    private javax.swing.JButton cargar;
    private javax.swing.JButton crearPartida;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFileChooser fileChooserOpen;
    private javax.swing.JButton five_0;
    private javax.swing.JButton five_1;
    private javax.swing.JButton five_2;
    private javax.swing.JButton five_3;
    private javax.swing.JButton five_4;
    private javax.swing.JButton five_5;
    private javax.swing.JButton five_6;
    private javax.swing.JButton five_7;
    private javax.swing.JButton four_0;
    private javax.swing.JButton four_1;
    private javax.swing.JButton four_2;
    private javax.swing.JButton four_3;
    private javax.swing.JButton four_4;
    private javax.swing.JButton four_5;
    private javax.swing.JButton four_6;
    private javax.swing.JButton four_7;
    private javax.swing.JPanel game;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton nextBtn1;
    private javax.swing.JButton one_0;
    private javax.swing.JButton one_1;
    private javax.swing.JButton one_2;
    private javax.swing.JButton one_3;
    private javax.swing.JButton one_4;
    private javax.swing.JButton one_5;
    private javax.swing.JButton one_6;
    private javax.swing.JButton one_7;
    private javax.swing.JPanel p1_preparation;
    private javax.swing.JPanel p2_attack_p1;
    private javax.swing.JPanel p2_preparation;
    private javax.swing.JTextArea player_one_prep_ships;
    private javax.swing.JTextArea player_two_prep_ships;
    private javax.swing.JButton seven_0;
    private javax.swing.JButton seven_1;
    private javax.swing.JButton seven_2;
    private javax.swing.JButton seven_3;
    private javax.swing.JButton seven_4;
    private javax.swing.JButton seven_5;
    private javax.swing.JButton seven_6;
    private javax.swing.JButton seven_7;
    private javax.swing.JButton six_0;
    private javax.swing.JButton six_1;
    private javax.swing.JButton six_2;
    private javax.swing.JButton six_3;
    private javax.swing.JButton six_4;
    private javax.swing.JButton six_5;
    private javax.swing.JButton six_6;
    private javax.swing.JButton six_7;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JButton three_0;
    private javax.swing.JButton three_1;
    private javax.swing.JButton three_2;
    private javax.swing.JButton three_3;
    private javax.swing.JButton three_4;
    private javax.swing.JButton three_5;
    private javax.swing.JButton three_6;
    private javax.swing.JButton three_7;
    private javax.swing.JLabel turnLabel;
    private javax.swing.JButton two_0;
    private javax.swing.JButton two_1;
    private javax.swing.JButton two_2;
    private javax.swing.JButton two_3;
    private javax.swing.JButton two_4;
    private javax.swing.JButton two_5;
    private javax.swing.JButton two_6;
    private javax.swing.JButton two_7;
    private javax.swing.JLabel winnerLabel;
    private javax.swing.JButton zero_0;
    private javax.swing.JButton zero_1;
    private javax.swing.JButton zero_2;
    private javax.swing.JButton zero_3;
    private javax.swing.JButton zero_4;
    private javax.swing.JButton zero_5;
    private javax.swing.JButton zero_6;
    private javax.swing.JButton zero_7;
    // End of variables declaration//GEN-END:variables
}
